### ISSUE TITLE
Conflict with Synergistic Traits mod

### ISSUE THREAD

**Issue by Mavdarez** [emipa606/PSReconditioningPod#2]
Synergistic Traits Loaded with Reconditioning Pod (Continued) throws this error:

Exception filling window for PS_ReconPod.PS_Panel_Reconditioning: System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.StatModifier.get_ToStringAsFactor () [0x00000] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
  at RimWorld.Trait.TipString (Verse.Pawn pawn) [0x00210] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
  at PS_ReconPod.PS_Panel_Reconditioning.<UpdateAddableTraits>b__37_0 (RimWorld.Trait trait) [0x00038] in <9caf88adfc394987afa8f0bb95b90314>:0 
  at System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].ToList () [0x0002a] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at PS_ReconPod.PS_Panel_Reconditioning.UpdateAddableTraits (System.Collections.Generic.List`1[T] currentTraits) [0x00020] in <9caf88adfc394987afa8f0bb95b90314>:0 
  at PS_ReconPod.PS_Panel_Reconditioning.Init (UnityEngine.Rect rect) [0x001cb] in <9caf88adfc394987afa8f0bb95b90314>:0 
  at PS_ReconPod.PS_Panel_Reconditioning.DoWindowContents (UnityEngine.Rect inRect) [0x00011] in <9caf88adfc394987afa8f0bb95b90314>:0 
  at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x00165] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
Verse.Log:Error(String, Boolean)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

Then this error which is spamed till it caps at 998 messeges  when you tell a colonist to get in a reconditioning pod:

Exception filling window for PS_ReconPod.PS_Panel_Reconditioning: System.NullReferenceException: Object reference not set to an instance of an object
  at PS_ReconPod.PS_ScrollView`1[T].Draw () [0x00037] in <9caf88adfc394987afa8f0bb95b90314>:0 
  at PS_ReconPod.PS_Panel_Reconditioning.DoWindowContents (UnityEngine.Rect inRect) [0x004fb] in <9caf88adfc394987afa8f0bb95b90314>:0 
  at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x00165] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0 
Verse.Log:Error(String, Boolean)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

The window to select what traits you want to add/remove, etc shows not traits anywhere and is blank, meaning that this conflict renders this mod more or less functionless. I was unable to get the hugslib logs for some reason with a server side error but this bug should be simple enough to recreate I've also let the other mod dev know as well in case it's something on there side that needs to be patched.

I got this mod to appear after veryifying file integrity, unsubscribing/resubscribing to both mods, putting Synergistic traits above and below in the load order, aall while starting a new game each time with just the pollowing mods loaded: Harmony, Core, Hugs Lib, Plasteel Surgery (Continued) [which is a requirement for reconditioning pods], Reconditioning Pods, and Synergistic Traits. I also tried to build the building with god mod on and by having the pawn build it with the materials which didn't affect anything.

Of course Reconditioning Pod (Continued mentions that some traits mods may not work if they do something to the strange traits so it could just be that in which case disregard this by letting me know if its just plain incompatible)
---

I also Get The following red errors upon loading the game (It's worth noting i do not have the royalty dlc and I'm using the most up to date and stable release of rimworld as of today):

Could not resolve cross-reference: No RimWorld.StatDef named PsychicEntropyMax found to give to RimWorld.StatModifier (null stat)
Verse.Log:Error(String, Boolean)
Verse.WantedRefForObject:TryResolve(FailMode)
Verse.<>c__DisplayClass15_1:<ResolveAllWantedCrossReferences>b__0(WantedRef)
Verse.<>c__DisplayClass6_1`1:<ParallelForEach>b__0(Object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

Could not resolve cross-reference: No RimWorld.StatDef named PsychicEntropyRecoveryRate found to give to RimWorld.StatModifier (null stat)
Verse.Log:Error(String, Boolean)
Verse.WantedRefForObject:TryResolve(FailMode)
Verse.<>c__DisplayClass15_1:<ResolveAllWantedCrossReferences>b__0(WantedRef)
Verse.<>c__DisplayClass6_1`1:<ParallelForEach>b__0(Object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
![02](https://user-images.githubusercontent.com/65970780/87883415-d0b11900-c9cc-11ea-8c94-006cac0d8416.PNG)

**Comment by Mavdarez** [comment]
p.s. I'd appreciate it if you could let me know via the discussion i opened in the steam page for your mod whenever you find out what the issue is or if it's just not compatible since i don't know how to 'subscribe' to this issue thread to be notified when you close it or reply, thanks.

p.p.s great work with all the revived mods your a boon to this community

**Comment by emipa606** [comment]
Tested with the latest version of Synergistic Traits and it seems this issue is resolved since the author of that mod removed the Royalty-traits.
